versoin: 1.0
containers:
  registry: quay.io/devtest
  images:
    - name: cellranger
      version: 6.1.1
      project_url: https://github.com/hisplan/docker-cellranger
      download_url: https://github.com/hisplan/docker-cellranger/archive/refs/tags/v6.1.1.tar.gz

pipelines:
  packages:
    - name: cellranger-vdj
      version: 6.1.1
      project_url: https://github.com/hisplan/wdl-cellranger-vdj
      download_url: https://github.com/hisplan/wdl-cellranger-vdj/archive/refs/tags/v6.1.1.tar.gz
